### ISSUE TITLE
Allow exception to have multiple causes

### ISSUE THREAD

**Issue by HuyaneMatsu** [HuyaneMatsu/scarletio#11]
Some exceptions might have multiple cause, but no builtin solution can resolve it.

Proposal:
```py3
raise Exception from CauseGroup(...)
```

The traceback renderer should pick up `CauseGroup` as a special case and render the cause accordingly.

**Comment by WizzyGeek** [comment]
This is being added in 3.11, see https://peps.python.org/pep-0654/

I tried it out myself
```
Python 3.11.0rc2 (main, Sep 11 2022, 20:22:52) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> raise Exception("a") from ExceptionGroup("one", [ValueError(1), TypeError("Wrong Type"), ExceptionGroup("two", [Exception("foo"), ValueError("bar")])])
  | ExceptionGroup: one (3 sub-exceptions)
  +-+---------------- 1 ----------------
    | ValueError: 1
    +---------------- 2 ----------------
    | TypeError: Wrong Type
    +---------------- 3 ----------------
    | ExceptionGroup: two (2 sub-exceptions)
    +-+---------------- 1 ----------------
      | Exception: foo
      +---------------- 2 ----------------
      | ValueError: bar
      +------------------------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
Exception: a
```

Do you intend to do this for backwards compatibility with Python3.11- ?

**Comment by HuyaneMatsu** [comment]
> Do you intend to do this for backwards compatibility with Python3.11- ?

1. I did not know they will add a familiar feature for this purpose.
2. I require the feature to produce a better tracebacks at rare cases.

**Comment by WizzyGeek** [comment]
> I require the feature to produce a better tracebacks at rare cases.

I hope that whatever you end up doing, you preserve some form of compatibility with the new `except*`

**Comment by HuyaneMatsu** [comment]
> I hope that whatever you end up doing, you preserve some form of compatibility with the new except*

This will only work as "cause" and not as "group", so if you want to use `except*`, you will be able to raise "group".

**Comment by HuyaneMatsu** [comment]
Added 🚀
