### ISSUE TITLE
Move Asyncio drop-in to Scarletio library

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [HuyaneMatsu/scarletio#6]
Hata has https://github.com/HuyaneMatsu/hata/tree/master/hata/ext/asyncio to easily allow the user to use any asyncio library with scarletio, but this would really be more in place here instead, as well as allowing the user to use existing asyncio libraries easily too

**Comment by HuyaneMatsu** [comment]
Pushed to github & pypi as well

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Nice!
