### ISSUE TITLE
Unimplemented methods of scarletio!

### ISSUE THREAD

**Issue by Yu-Vitaqua-fer-Chronos** [HuyaneMatsu/scarletio#7]
https://www.toptal.com/developers/hastebin/sohojozadu.py

I'm trying to run [neumond/python-computer-craft](https://github.com/neumond/python-computer-craft) with scarletio, but there's still some unimplemented methods, here's the code:
```python
try:
    from scarletio.ext import asyncio
except ImportError:
    print("WARNING: Scarletio could not be imported! Performance may be degraded!")

from computercraft.server import main as ccserver

ccserver()
```

**Comment by HuyaneMatsu** [comment]
Thanks for reporting this issue.

**Comment by HuyaneMatsu** [comment]
The missing methods have been added. The fix will be alive in the next update.
