### ISSUE TITLE
Error in SyncQueue.copy

### ISSUE THREAD

**Issue by WizzyGeek** [HuyaneMatsu/scarletio#8]
https://github.com/HuyaneMatsu/scarletio/blob/577920c34a8c1720d8a7bd0fa96f4ab713de1558/scarletio/core/event_loop/executor.py#L315

seems like `new` is `None` unless it uses black magic

**Comment by HuyaneMatsu** [comment]
yupp, thats a bug, will fix.

**Comment by HuyaneMatsu** [comment]
Fixed 👍🏻
